//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBox_3D.BrailleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrailleServiceReference.BrailleServiceSoap")]
    public interface BrailleServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToBraille", ReplyAction="*")]
        SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponse ConvertToBraille(SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToBraille", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponse> ConvertToBrailleAsync(SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDotsAmount", ReplyAction="*")]
        SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse GetDotsAmount(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDotsAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse> GetDotsAmountAsync(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToBrailleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToBraille", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequestBody Body;
        
        public ConvertToBrailleRequest() {
        }
        
        public ConvertToBrailleRequest(SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToBrailleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public ConvertToBrailleRequestBody() {
        }
        
        public ConvertToBrailleRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToBrailleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToBrailleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponseBody Body;
        
        public ConvertToBrailleResponse() {
        }
        
        public ConvertToBrailleResponse(SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToBrailleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertToBrailleResult;
        
        public ConvertToBrailleResponseBody() {
        }
        
        public ConvertToBrailleResponseBody(string ConvertToBrailleResult) {
            this.ConvertToBrailleResult = ConvertToBrailleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDotsAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDotsAmount", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody Body;
        
        public GetDotsAmountRequest() {
        }
        
        public GetDotsAmountRequest(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDotsAmountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetDotsAmountRequestBody() {
        }
        
        public GetDotsAmountRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDotsAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDotsAmountResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponseBody Body;
        
        public GetDotsAmountResponse() {
        }
        
        public GetDotsAmountResponse(SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDotsAmountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDotsAmountResult;
        
        public GetDotsAmountResponseBody() {
        }
        
        public GetDotsAmountResponseBody(int GetDotsAmountResult) {
            this.GetDotsAmountResult = GetDotsAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BrailleServiceSoapChannel : SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrailleServiceSoapClient : System.ServiceModel.ClientBase<SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap>, SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap {
        
        public BrailleServiceSoapClient() {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponse SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.ConvertToBraille(SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest request) {
            return base.Channel.ConvertToBraille(request);
        }
        
        public string ConvertToBraille(string input) {
            SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest inValue = new SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequestBody();
            inValue.Body.input = input;
            SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponse retVal = ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).ConvertToBraille(inValue);
            return retVal.Body.ConvertToBrailleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponse> SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.ConvertToBrailleAsync(SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest request) {
            return base.Channel.ConvertToBrailleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.ConvertToBrailleResponse> ConvertToBrailleAsync(string input) {
            SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest inValue = new SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.ConvertToBrailleRequestBody();
            inValue.Body.input = input;
            return ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).ConvertToBrailleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.GetDotsAmount(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request) {
            return base.Channel.GetDotsAmount(request);
        }
        
        public int GetDotsAmount(string input) {
            SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest inValue = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody();
            inValue.Body.input = input;
            SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse retVal = ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).GetDotsAmount(inValue);
            return retVal.Body.GetDotsAmountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse> SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap.GetDotsAmountAsync(SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest request) {
            return base.Channel.GetDotsAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.BrailleServiceReference.GetDotsAmountResponse> GetDotsAmountAsync(string input) {
            SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest inValue = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequest();
            inValue.Body = new SpaceBox_3D.BrailleServiceReference.GetDotsAmountRequestBody();
            inValue.Body.input = input;
            return ((SpaceBox_3D.BrailleServiceReference.BrailleServiceSoap)(this)).GetDotsAmountAsync(inValue);
        }
    }
}
