//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBox_3D.BrailleConverter {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrailleConverter.BrailleConverterSoap")]
    public interface BrailleConverterSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToBraille", ReplyAction="*")]
        SpaceBox_3D.BrailleConverter.ConvertToBrailleResponse ConvertToBraille(SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToBraille", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleConverter.ConvertToBrailleResponse> ConvertToBrailleAsync(SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToBrailleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToBraille", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleConverter.ConvertToBrailleRequestBody Body;
        
        public ConvertToBrailleRequest() {
        }
        
        public ConvertToBrailleRequest(SpaceBox_3D.BrailleConverter.ConvertToBrailleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToBrailleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public ConvertToBrailleRequestBody() {
        }
        
        public ConvertToBrailleRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertToBrailleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertToBrailleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.BrailleConverter.ConvertToBrailleResponseBody Body;
        
        public ConvertToBrailleResponse() {
        }
        
        public ConvertToBrailleResponse(SpaceBox_3D.BrailleConverter.ConvertToBrailleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertToBrailleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertToBrailleResult;
        
        public ConvertToBrailleResponseBody() {
        }
        
        public ConvertToBrailleResponseBody(string ConvertToBrailleResult) {
            this.ConvertToBrailleResult = ConvertToBrailleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BrailleConverterSoapChannel : SpaceBox_3D.BrailleConverter.BrailleConverterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrailleConverterSoapClient : System.ServiceModel.ClientBase<SpaceBox_3D.BrailleConverter.BrailleConverterSoap>, SpaceBox_3D.BrailleConverter.BrailleConverterSoap {
        
        public BrailleConverterSoapClient() {
        }
        
        public BrailleConverterSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrailleConverterSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleConverterSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrailleConverterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.BrailleConverter.ConvertToBrailleResponse SpaceBox_3D.BrailleConverter.BrailleConverterSoap.ConvertToBraille(SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest request) {
            return base.Channel.ConvertToBraille(request);
        }
        
        public string ConvertToBraille(string input) {
            SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest inValue = new SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleConverter.ConvertToBrailleRequestBody();
            inValue.Body.input = input;
            SpaceBox_3D.BrailleConverter.ConvertToBrailleResponse retVal = ((SpaceBox_3D.BrailleConverter.BrailleConverterSoap)(this)).ConvertToBraille(inValue);
            return retVal.Body.ConvertToBrailleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.BrailleConverter.ConvertToBrailleResponse> SpaceBox_3D.BrailleConverter.BrailleConverterSoap.ConvertToBrailleAsync(SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest request) {
            return base.Channel.ConvertToBrailleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.BrailleConverter.ConvertToBrailleResponse> ConvertToBrailleAsync(string input) {
            SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest inValue = new SpaceBox_3D.BrailleConverter.ConvertToBrailleRequest();
            inValue.Body = new SpaceBox_3D.BrailleConverter.ConvertToBrailleRequestBody();
            inValue.Body.input = input;
            return ((SpaceBox_3D.BrailleConverter.BrailleConverterSoap)(this)).ConvertToBrailleAsync(inValue);
        }
    }
}
