//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBox_3D.ShapesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShapesServiceReference.ShapesServiceSoap")]
    public interface ShapesServiceSoap {
        
        // CODEGEN: Generating message contract since element name shapeType from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountBrailleDots", ReplyAction="*")]
        SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponse CountBrailleDots(SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CountBrailleDots", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponse> CountBrailleDotsAsync(SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountBrailleDotsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountBrailleDots", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequestBody Body;
        
        public CountBrailleDotsRequest() {
        }
        
        public CountBrailleDotsRequest(SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountBrailleDotsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shapeType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double radius;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double length;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double side_a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double side_b;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double side_c;
        
        public CountBrailleDotsRequestBody() {
        }
        
        public CountBrailleDotsRequestBody(string shapeType, double radius, double length, double width, double side_a, double side_b, double side_c) {
            this.shapeType = shapeType;
            this.radius = radius;
            this.length = length;
            this.width = width;
            this.side_a = side_a;
            this.side_b = side_b;
            this.side_c = side_c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CountBrailleDotsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CountBrailleDotsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponseBody Body;
        
        public CountBrailleDotsResponse() {
        }
        
        public CountBrailleDotsResponse(SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CountBrailleDotsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CountBrailleDotsResult;
        
        public CountBrailleDotsResponseBody() {
        }
        
        public CountBrailleDotsResponseBody(int CountBrailleDotsResult) {
            this.CountBrailleDotsResult = CountBrailleDotsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShapesServiceSoapChannel : SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShapesServiceSoapClient : System.ServiceModel.ClientBase<SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap>, SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap {
        
        public ShapesServiceSoapClient() {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponse SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap.CountBrailleDots(SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest request) {
            return base.Channel.CountBrailleDots(request);
        }
        
        public int CountBrailleDots(string shapeType, double radius, double length, double width, double side_a, double side_b, double side_c) {
            SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest inValue = new SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest();
            inValue.Body = new SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequestBody();
            inValue.Body.shapeType = shapeType;
            inValue.Body.radius = radius;
            inValue.Body.length = length;
            inValue.Body.width = width;
            inValue.Body.side_a = side_a;
            inValue.Body.side_b = side_b;
            inValue.Body.side_c = side_c;
            SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponse retVal = ((SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap)(this)).CountBrailleDots(inValue);
            return retVal.Body.CountBrailleDotsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponse> SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap.CountBrailleDotsAsync(SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest request) {
            return base.Channel.CountBrailleDotsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CountBrailleDotsResponse> CountBrailleDotsAsync(string shapeType, double radius, double length, double width, double side_a, double side_b, double side_c) {
            SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest inValue = new SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequest();
            inValue.Body = new SpaceBox_3D.ShapesServiceReference.CountBrailleDotsRequestBody();
            inValue.Body.shapeType = shapeType;
            inValue.Body.radius = radius;
            inValue.Body.length = length;
            inValue.Body.width = width;
            inValue.Body.side_a = side_a;
            inValue.Body.side_b = side_b;
            inValue.Body.side_c = side_c;
            return ((SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap)(this)).CountBrailleDotsAsync(inValue);
        }
    }
}
