//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBox_3D.ShapesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShapesServiceReference.ShapesServiceSoap")]
    public interface ShapesServiceSoap {
        
        // CODEGEN: Generating message contract since element name shape from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateDotAmount", ReplyAction="*")]
        SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponse CalculateDotAmount(SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculateDotAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponse> CalculateDotAmountAsync(SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateDotAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateDotAmount", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequestBody Body;
        
        public CalculateDotAmountRequest() {
        }
        
        public CalculateDotAmountRequest(SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateDotAmountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shape;
        
        public CalculateDotAmountRequestBody() {
        }
        
        public CalculateDotAmountRequestBody(string shape) {
            this.shape = shape;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateDotAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateDotAmountResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponseBody Body;
        
        public CalculateDotAmountResponse() {
        }
        
        public CalculateDotAmountResponse(SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateDotAmountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CalculateDotAmountResult;
        
        public CalculateDotAmountResponseBody() {
        }
        
        public CalculateDotAmountResponseBody(int CalculateDotAmountResult) {
            this.CalculateDotAmountResult = CalculateDotAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShapesServiceSoapChannel : SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShapesServiceSoapClient : System.ServiceModel.ClientBase<SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap>, SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap {
        
        public ShapesServiceSoapClient() {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponse SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap.CalculateDotAmount(SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest request) {
            return base.Channel.CalculateDotAmount(request);
        }
        
        public int CalculateDotAmount(string shape) {
            SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest inValue = new SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest();
            inValue.Body = new SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequestBody();
            inValue.Body.shape = shape;
            SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponse retVal = ((SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap)(this)).CalculateDotAmount(inValue);
            return retVal.Body.CalculateDotAmountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponse> SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap.CalculateDotAmountAsync(SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest request) {
            return base.Channel.CalculateDotAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CalculateDotAmountResponse> CalculateDotAmountAsync(string shape) {
            SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest inValue = new SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequest();
            inValue.Body = new SpaceBox_3D.ShapesServiceReference.CalculateDotAmountRequestBody();
            inValue.Body.shape = shape;
            return ((SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap)(this)).CalculateDotAmountAsync(inValue);
        }
    }
}
