//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceBox_3D.ShapesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShapesServiceReference.ShapesServiceSoap")]
    public interface ShapesServiceSoap {
        
        // CODEGEN: Generating message contract since element name CreateCircleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCircle", ReplyAction="*")]
        SpaceBox_3D.ShapesServiceReference.CreateCircleResponse CreateCircle(SpaceBox_3D.ShapesServiceReference.CreateCircleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCircle", ReplyAction="*")]
        System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CreateCircleResponse> CreateCircleAsync(SpaceBox_3D.ShapesServiceReference.CreateCircleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCircleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCircle", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.ShapesServiceReference.CreateCircleRequestBody Body;
        
        public CreateCircleRequest() {
        }
        
        public CreateCircleRequest(SpaceBox_3D.ShapesServiceReference.CreateCircleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateCircleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double radius;
        
        public CreateCircleRequestBody() {
        }
        
        public CreateCircleRequestBody(double radius) {
            this.radius = radius;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateCircleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateCircleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SpaceBox_3D.ShapesServiceReference.CreateCircleResponseBody Body;
        
        public CreateCircleResponse() {
        }
        
        public CreateCircleResponse(SpaceBox_3D.ShapesServiceReference.CreateCircleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateCircleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateCircleResult;
        
        public CreateCircleResponseBody() {
        }
        
        public CreateCircleResponseBody(string CreateCircleResult) {
            this.CreateCircleResult = CreateCircleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShapesServiceSoapChannel : SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShapesServiceSoapClient : System.ServiceModel.ClientBase<SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap>, SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap {
        
        public ShapesServiceSoapClient() {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShapesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SpaceBox_3D.ShapesServiceReference.CreateCircleResponse SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap.CreateCircle(SpaceBox_3D.ShapesServiceReference.CreateCircleRequest request) {
            return base.Channel.CreateCircle(request);
        }
        
        public string CreateCircle(double radius) {
            SpaceBox_3D.ShapesServiceReference.CreateCircleRequest inValue = new SpaceBox_3D.ShapesServiceReference.CreateCircleRequest();
            inValue.Body = new SpaceBox_3D.ShapesServiceReference.CreateCircleRequestBody();
            inValue.Body.radius = radius;
            SpaceBox_3D.ShapesServiceReference.CreateCircleResponse retVal = ((SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap)(this)).CreateCircle(inValue);
            return retVal.Body.CreateCircleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CreateCircleResponse> SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap.CreateCircleAsync(SpaceBox_3D.ShapesServiceReference.CreateCircleRequest request) {
            return base.Channel.CreateCircleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SpaceBox_3D.ShapesServiceReference.CreateCircleResponse> CreateCircleAsync(double radius) {
            SpaceBox_3D.ShapesServiceReference.CreateCircleRequest inValue = new SpaceBox_3D.ShapesServiceReference.CreateCircleRequest();
            inValue.Body = new SpaceBox_3D.ShapesServiceReference.CreateCircleRequestBody();
            inValue.Body.radius = radius;
            return ((SpaceBox_3D.ShapesServiceReference.ShapesServiceSoap)(this)).CreateCircleAsync(inValue);
        }
    }
}
